# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.box = "hashicorp/precise32"
	config.vm.network :forwarded_port, host: 27017, guest: 27017, run: "always"

	config.vm.synced_folder "../../", "/var/puppetory"
	
	config.vm.provision "shell", path: "../scripts/init-db.sh"
end
